### ISSUE TITLE
Tree breaking in IE 11: 'Symbol' is undefined

### ISSUE THREAD

**Issue by saydmateen** [deltoss/d3-mitch-tree#16]
When I load the tree in IE 11 it throw's an error and doesn't' allow the tree to load. Installing the babel/polyfill fixes the issue but I can't include an extra library at the moment. Do you know which function is causing the issue so I could manually create the polyfill?

![image](https://user-images.githubusercontent.com/32889475/70278841-e0475e80-1769-11ea-94c1-cd1e0e529efa.png)

**Comment by saydmateen** [comment]
I believe it's caused by a bug with the latest version of Babel? 
https://github.com/babel/babel/pull/8947

**Comment by deltoss** [comment]
The error occurs due to the fact polyfills aren't included as part of the plugin. I would love to include it (I did for the `IE11-Fix-Attempt` branch), but there's no point as even if I did, the plugin doesn't behave as expected on IE 11.

For example, among other things, the texts could go missing:

![image](https://user-images.githubusercontent.com/9282390/70375690-e2b9dc00-1954-11ea-891f-9218f2205914.png)

If you'd like IE 11 support, feel free to submit a PR for the below branch:
https://github.com/deltoss/d3-mitch-tree/tree/feature/IE11-Fix-Attempt

**Comment by saydmateen** [comment]
Sounds good, I will take a look at the branch and let you know what I find. Thanks.
